import { CareArticleCardData } from "./CareArticleCard";

export const BUDGIE_CARE_ARTICLES: CareArticleCardData[] = [
  {
    id: "best-foods-for-budgies",
    title: "Best Foods for Budgies",
    excerpt: "Learn what to feed your budgie for optimal health, energy and a long life.",
    readTime: "6 min read",
    category: "Nutrition",
    image: "/CareGuide/articles/budgie/best-foods.jpg",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
  {
    id: "common-health-issues-budgies",
    title: "Common Health Issues in Budgies",
    excerpt: "Spot the signs early and know when to see a vet.",
    readTime: "7 min read",
    category: "Health & Vet Care",
    image: "/CareGuide/articles/budgie/health-issues.jpg",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
  {
    id: "bonding-training-budgie",
    title: "Bonding & Training Your Budgie",
    excerpt: "Build trust, encourage good behavior and enjoy a stronger bond.",
    readTime: "7 min read",
    category: "Training",
    image: "/CareGuide/articles/budgie/bonding-training.jpg",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
  {
    id: "bathing-your-budgie",
    title: "Bathing Your Budgie",
    excerpt: "Keep your bird clean, healthy and feathered beautifully.",
    readTime: "5 min read",
    category: "Grooming",
    image: "/CareGuide/articles/budgie/bathing.jpg",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
  {
    id: "understanding-budgie-behavior",
    title: "Understanding Budgie Behavior",
    excerpt: "Decode their body language and what they're really trying to tell you.",
    readTime: "6 min read",
    category: "Behavior",
    image: "/CareGuide/articles/budgie/behavior.jpg",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
  {
    id: "caring-for-baby-budgies",
    title: "Caring for Baby Budgies",
    excerpt: "From hatching to fledging — week by week care guide.",
    readTime: "8 min read",
    category: "Life Stage",
    image: "/CareGuide/articles/budgie/baby-budgies.jpg",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
  {
    id: "vaccinations-preventive-care",
    title: "Vaccinations & Preventive Care",
    excerpt: "Keep your budgie protected and living a longer, healthier life.",
    readTime: "7 min read",
    category: "Health & Vet Care",
    image: "/CareGuide/articles/budgie/vaccinations.jpg",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
  {
    id: "safe-unsafe-foods",
    title: "Safe & Unsafe Foods",
    excerpt: "What your budgie can and can't eat (and why it matters).",
    readTime: "5 min read",
    category: "Nutrition",
    image: "/CareGuide/articles/budgie/safe-unsafe-foods.jpg",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
];

export const DOG_CARE_ARTICLES: CareArticleCardData[] = [
  {
    id: "puppy-vaccination-schedule",
    title: "Puppy Vaccination Schedule & Milestones",
    excerpt: "Core vaccines, optional boosters, and safe socialization timelines for your pup.",
    readTime: "7 min read",
    category: "Health & Vet Care",
    image: "/CareGuide/breeds/dogs/golden-retriever.jpg",
    expertReviewed: true,
    slug: "puppy-vaccination-schedule-guide",
  },
  {
    id: "raw-vs-grain-inclusive-dog-diets",
    title: "Raw vs. Grain-Inclusive Dog Diets",
    excerpt: "A vet-evaluated breakdown of complete canine nutritional requirements.",
    readTime: "9 min read",
    category: "Nutrition",
    image: "/CareGuide/breeds/dogs/labrador.jpg",
    expertReviewed: true,
    slug: "raw-vs-grain-inclusive-dog-diets",
  },
  {
    id: "positive-reinforcement-training",
    title: "Positive Reinforcement Training 101",
    excerpt: "Build lifelong trust and manners using clicker and treat reward methods.",
    readTime: "6 min read",
    category: "Training",
    image: "/CareGuide/breeds/dogs/poodle.jpg",
    expertReviewed: true,
    slug: "puppy-vaccination-schedule-guide",
  },
  {
    id: "heatstroke-prevention-dogs",
    title: "Heatstroke Prevention in Flat-Faced Breeds",
    excerpt: "Warning indicators, cooling strategies, and emergency first-aid protocols.",
    readTime: "5 min read",
    category: "Health & Vet Care",
    image: "/CareGuide/breeds/dogs/french-bulldog.jpg",
    expertReviewed: true,
    slug: "summer-heatstroke-prevention-flat-faced-dogs",
  },
  {
    id: "brushing-deshedding-care",
    title: "Coat Brushing & Deshedding Fundamentals",
    excerpt: "Keep double coats mats-free and skin healthy through seasonal coat blowouts.",
    readTime: "6 min read",
    category: "Grooming",
    image: "/CareGuide/breeds/dogs/husky.jpg",
    expertReviewed: true,
    slug: "puppy-vaccination-schedule-guide",
  },
  {
    id: "canine-separation-anxiety",
    title: "Recognizing & Calming Separation Anxiety",
    excerpt: "Proven desensitization cues to help your dog relax while home alone.",
    readTime: "8 min read",
    category: "Behavior",
    image: "/CareGuide/breeds/dogs/corgi.jpg",
    expertReviewed: true,
    slug: "puppy-vaccination-schedule-guide",
  },
  {
    id: "senior-dog-joint-wellness",
    title: "Senior Dog Joint Mobility & Comfort",
    excerpt: "Supplements, orthopedic support, and gentle exercise for older dogs.",
    readTime: "7 min read",
    category: "Life Stage",
    image: "/CareGuide/breeds/dogs/german-shepherd.jpg",
    expertReviewed: true,
    slug: "puppy-vaccination-schedule-guide",
  },
  {
    id: "toxic-household-foods-dogs",
    title: "Toxic Foods Your Dog Must Never Ingest",
    excerpt: "The critical vet list of dangerous kitchen staples and toxic ingredients.",
    readTime: "5 min read",
    category: "Nutrition",
    image: "/CareGuide/breeds/dogs/beagle.jpg",
    expertReviewed: true,
    slug: "raw-vs-grain-inclusive-dog-diets",
  },
];

export const CAT_CARE_ARTICLES: CareArticleCardData[] = [
  {
    id: "teach-kitten-simple-cues",
    title: "Teach Your New Kitten Simple Cues",
    excerpt: "Target stick training, gentle recall, and rewarding polite manners in cats.",
    readTime: "6 min read",
    category: "Training",
    image: "/CareGuide/breeds/cats/persian.jpg",
    expertReviewed: true,
    slug: "teach-new-kitten-simple-cues",
  },
  {
    id: "feline-urinary-tract-health",
    title: "Feline Hydration & Urinary Tract Health",
    excerpt: "Wet food moisture ratios, fountains, and early indicators of FLUTD.",
    readTime: "7 min read",
    category: "Health & Vet Care",
    image: "/CareGuide/breeds/cats/british-shorthair.jpg",
    expertReviewed: true,
    slug: "teach-new-kitten-simple-cues",
  },
  {
    id: "scratching-post-mastery",
    title: "Scratching Post Selection & Cat Body Language",
    excerpt: "Understand scent marking and how to redirect clawing instincts safely.",
    readTime: "5 min read",
    category: "Behavior",
    image: "/CareGuide/breeds/cats/siamese.jpg",
    expertReviewed: true,
    slug: "teach-new-kitten-simple-cues",
  },
  {
    id: "brushing-longhaired-cats",
    title: "Grooming Long-Haired Breeds Without Stress",
    excerpt: "Preventing hairballs, detangling dense ruffs, and claw maintenance tips.",
    readTime: "6 min read",
    category: "Grooming",
    image: "/CareGuide/breeds/cats/maine-coon.jpg",
    expertReviewed: true,
    slug: "teach-new-kitten-simple-cues",
  },
  {
    id: "indoor-enrichment-for-cats",
    title: "Vertical Spaces & Indoor Enrichment",
    excerpt: "Cat wall perches, puzzle feeders, and hunting play sequences for bored felines.",
    readTime: "8 min read",
    category: "Behavior",
    image: "/CareGuide/breeds/cats/bengal.jpg",
    expertReviewed: true,
    slug: "teach-new-kitten-simple-cues",
  },
  {
    id: "kitten-first-year-milestones",
    title: "First-Year Kitten Growth & Nutrition",
    excerpt: "High-protein feeding curves, spay/neuter healing, and socialization windows.",
    readTime: "7 min read",
    category: "Life Stage",
    image: "/CareGuide/breeds/cats/ragdoll.jpg",
    expertReviewed: true,
    slug: "teach-new-kitten-simple-cues",
  },
  {
    id: "hairball-dietary-prevention",
    title: "Hairball Remedies & Balanced Fiber Diets",
    excerpt: "Fiber blends and digestive enzymatics that ease hairball passage naturally.",
    readTime: "5 min read",
    category: "Nutrition",
    image: "/CareGuide/breeds/cats/russian-blue.jpg",
    expertReviewed: true,
    slug: "teach-new-kitten-simple-cues",
  },
  {
    id: "dental-hygiene-in-cats",
    title: "Preventing Periodontal Disease in Cats",
    excerpt: "Enzymatic tooth gels, dental treats, and annual vet scale checks.",
    readTime: "6 min read",
    category: "Health & Vet Care",
    image: "/CareGuide/breeds/cats/scottish-fold.jpg",
    expertReviewed: true,
    slug: "teach-new-kitten-simple-cues",
  },
];

export const CATEGORY_ARTICLES_MAP: Record<string, CareArticleCardData[]> = {
  birds: BUDGIE_CARE_ARTICLES,
  dogs: DOG_CARE_ARTICLES,
  cats: CAT_CARE_ARTICLES,
};
