import { CareArticleCardData } from "./CareArticleCard";

export const BUDGIE_CARE_ARTICLES: CareArticleCardData[] = [
  {
    id: "best-foods-for-budgies",
    title: "Best Foods for Budgies",
    excerpt: "Learn what to feed your budgie for optimal health, balanced metabolism, vibrant plumage, and a long life with fresh greens and seeds.",
    readTime: "6 min read",
    category: "Nutrition",
    image: "/CareGuide/articles/budgie/best-foods.jpg",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
  {
    id: "common-health-issues-budgies",
    title: "Common Health Issues in Budgies",
    excerpt: "Spot respiratory distress, tail bobbing, and lethargy signs early so you know exactly when to consult an avian veterinarian.",
    readTime: "7 min read",
    category: "Health & Vet Care",
    image: "/CareGuide/articles/budgie/health-issues.jpg",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
  {
    id: "bonding-training-budgie",
    title: "Bonding & Training Your Budgie",
    excerpt: "Build trust with millet rewards, encourage confident step-up behavior, and develop a calm, affectionate lifelong companionship.",
    readTime: "7 min read",
    category: "Training",
    image: "/CareGuide/articles/budgie/bonding-training.jpg",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
  {
    id: "bathing-your-budgie",
    title: "Bathing Your Budgie",
    excerpt: "Keep your bird clean, prevent feather dander irritation, and maintain beautiful, glossy plumage through gentle water misting.",
    readTime: "5 min read",
    category: "Grooming",
    image: "/CareGuide/articles/budgie/bathing.jpg",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
  {
    id: "understanding-budgie-behavior",
    title: "Understanding Budgie Behavior",
    excerpt: "Decode beak grinding, head bobbing, and wing flapping to understand their exact mood, comfort, and socialization needs.",
    readTime: "6 min read",
    category: "Behavior",
    image: "/CareGuide/articles/budgie/behavior.jpg",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
  {
    id: "caring-for-baby-budgies",
    title: "Caring for Baby Budgies",
    excerpt: "From hatchling nest box warmth to first fledgling flights — essential week-by-week crop checks and hand-feeding protocols.",
    readTime: "8 min read",
    category: "Life Stage",
    image: "/CareGuide/articles/budgie/baby-budgies.jpg",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
  {
    id: "vaccinations-preventive-care",
    title: "Vaccinations & Preventive Care",
    excerpt: "Shield your flock against polyomavirus, psittacosis, and mite infestations with routine avian wellness exams and sanitation.",
    readTime: "7 min read",
    category: "Health & Vet Care",
    image: "/CareGuide/articles/budgie/vaccinations.jpg",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
  {
    id: "safe-unsafe-foods",
    title: "Safe & Unsafe Foods",
    excerpt: "Crucial vet guidelines on toxic ingredients like avocado, onion, and chocolate versus nutrient-dense dark leafy greens and sprouted grains.",
    readTime: "5 min read",
    category: "Nutrition",
    image: "/CareGuide/articles/budgie/safe-unsafe-foods.jpg",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
  {
    id: "cockatiel-whistling-sound-training",
    title: "Cockatiel Vocal Training & Song Mimicry",
    excerpt: "Teach tunes, repetitive whistles, and cheerful melodic calls using positive reinforcement and calm vocal mirroring exercises.",
    readTime: "6 min read",
    category: "Training",
    image: "/CareGuide/breeds/birds/cockatiel.jpg",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
  {
    id: "macaw-large-parrot-mental-enrichment",
    title: "Foraging & Destructive Play for Parrots",
    excerpt: "Satisfy powerful beak instincts, prevent feather plucking, and foster curiosity with hardwood chew puzzles and foraging bowls.",
    readTime: "8 min read",
    category: "Behavior",
    image: "/CareGuide/breeds/birds/macaw.jpg",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
  {
    id: "conure-screaming-contact-calls",
    title: "Deciphering Conure Contact Calls vs. Screaming",
    excerpt: "Distinguish cheerful flock check-ins from boredom-induced alarm screams, and learn how to reward quiet vocalizations.",
    readTime: "5 min read",
    category: "Behavior",
    image: "/CareGuide/breeds/birds/conure.jpg",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
  {
    id: "lovebird-pair-bonding-hormone-balance",
    title: "Lovebird Social Dynamics & Nest Box Care",
    excerpt: "Manage territorial aggression, seasonal hormonal spikes, and day-night lighting schedules to maintain harmonious cage life.",
    readTime: "7 min read",
    category: "Life Stage",
    image: "/CareGuide/breeds/birds/lovebird.jpg",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
  {
    id: "african-grey-cognitive-puzzles",
    title: "African Grey Speech Development & Puzzles",
    excerpt: "Engage world-class avian intellect with associative color recognition toys, word association drills, and structured daily interaction.",
    readTime: "9 min read",
    category: "Training",
    image: "/CareGuide/breeds/birds/african-grey.jpg",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
  {
    id: "canary-singing-diet-lighting",
    title: "Canary Melodic Song & Molting Nutrition",
    excerpt: "Support singing vigor and brilliant yellow feather luster with protein-rich egg food, rape seed blends, and natural daylight cycles.",
    readTime: "6 min read",
    category: "Nutrition",
    image: "/CareGuide/breeds/birds/canary.jpg",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
  {
    id: "finch-colony-flight-cages",
    title: "Gouldian Finch Colony & Flight Cage Setup",
    excerpt: "Create spacious horizontal flight corridors, live non-toxic perches, and quiet nesting pockets for calm, social waxbill finches.",
    readTime: "6 min read",
    category: "General Care",
    image: "/CareGuide/breeds/birds/finch.jpg",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
  {
    id: "cockatoo-cuddle-dependency-balance",
    title: "Cockatoo Emotional Wellness & Cuddle Balance",
    excerpt: "Prevent scream-for-attention habits and severe separation distress by teaching independent foraging and toy shredding early.",
    readTime: "8 min read",
    category: "Behavior",
    image: "/CareGuide/breeds/birds/cockatoo.jpg",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
];

export const DOG_CARE_ARTICLES: CareArticleCardData[] = [
  {
    id: "puppy-vaccination-schedule",
    title: "Puppy Vaccination Schedule & Milestones",
    excerpt: "Comprehensive timeline for DHPP, Rabies, Bordetella boosters, and safe socialization windows to protect your puppy from contagious parvovirus.",
    readTime: "7 min read",
    category: "Health & Vet Care",
    image: "/CareGuide/breeds/dogs/golden-retriever.jpg",
    expertReviewed: true,
    slug: "puppy-vaccination-schedule-guide",
  },
  {
    id: "raw-vs-grain-inclusive-dog-diets",
    title: "Raw vs. Grain-Inclusive Dog Diets",
    excerpt: "A vet-evaluated breakdown of balanced macro ratios, taurine heart wellness, bone safety, and commercial raw pathogen safety protocols.",
    readTime: "9 min read",
    category: "Nutrition",
    image: "/CareGuide/breeds/dogs/labrador.jpg",
    expertReviewed: true,
    slug: "raw-vs-grain-inclusive-dog-diets",
  },
  {
    id: "positive-reinforcement-training",
    title: "Positive Reinforcement Training 101",
    excerpt: "Build reliable loose-leash walking, instant recall, and polite greeting manners using clicker markers and high-value reward schedules.",
    readTime: "6 min read",
    category: "Training",
    image: "/CareGuide/breeds/dogs/poodle.jpg",
    expertReviewed: true,
    slug: "puppy-vaccination-schedule-guide",
  },
  {
    id: "heatstroke-prevention-dogs",
    title: "Heatstroke Prevention in Flat-Faced Breeds",
    excerpt: "Life-saving cooling strategies, asphalt temperature checks, and emergency symptom recognitions tailored for brachycephalic dogs.",
    readTime: "5 min read",
    category: "Health & Vet Care",
    image: "/CareGuide/breeds/dogs/french-bulldog.jpg",
    expertReviewed: true,
    slug: "summer-heatstroke-prevention-flat-faced-dogs",
  },
  {
    id: "brushing-deshedding-care",
    title: "Coat Brushing & Deshedding Fundamentals",
    excerpt: "Prevent painful undercoat mats, maintain natural thermo-regulation, and minimize seasonal blowout hair with undercoat rakes and slickers.",
    readTime: "6 min read",
    category: "Grooming",
    image: "/CareGuide/breeds/dogs/husky.jpg",
    expertReviewed: true,
    slug: "puppy-vaccination-schedule-guide",
  },
  {
    id: "canine-separation-anxiety",
    title: "Recognizing & Calming Separation Anxiety",
    excerpt: "Step-by-step gradual departure conditioning, lick mat calming routines, and counter-conditioning cues to soothe home-alone stress.",
    readTime: "8 min read",
    category: "Behavior",
    image: "/CareGuide/breeds/dogs/corgi.jpg",
    expertReviewed: true,
    slug: "puppy-vaccination-schedule-guide",
  },
  {
    id: "senior-dog-joint-wellness",
    title: "Senior Dog Joint Mobility & Comfort",
    excerpt: "Glucosamine, chondroitin, and omega-3 regimens paired with low-impact hydrotherapy exercises to keep aging dogs active and pain-free.",
    readTime: "7 min read",
    category: "Life Stage",
    image: "/CareGuide/breeds/dogs/german-shepherd.jpg",
    expertReviewed: true,
    slug: "puppy-vaccination-schedule-guide",
  },
  {
    id: "toxic-household-foods-dogs",
    title: "Toxic Foods Your Dog Must Never Ingest",
    excerpt: "Detailed toxicology guide on xylitol sweeteners, grapes, chocolate, macadamia nuts, and allium species with immediate antidote guidance.",
    readTime: "5 min read",
    category: "Nutrition",
    image: "/CareGuide/breeds/dogs/beagle.jpg",
    expertReviewed: true,
    slug: "raw-vs-grain-inclusive-dog-diets",
  },
  {
    id: "crate-training-potty-schedule",
    title: "Crate Training & Overnight Potty Schedules",
    excerpt: "Turn the crate into an inviting personal den that eliminates nighttime accidents, speeds housebreaking, and promotes deep restful sleep.",
    readTime: "6 min read",
    category: "Training",
    image: "/CareGuide/breeds/dogs/rottweiler.jpg",
    expertReviewed: true,
    slug: "puppy-vaccination-schedule-guide",
  },
  {
    id: "dental-chews-and-brushing",
    title: "Canine Dental Plaque & Brushing Secrets",
    excerpt: "Combat chronic halitosis, tartar calcification, and systemic gum infections using pet-safe poultry enzymatics and textured chews.",
    readTime: "5 min read",
    category: "Grooming",
    image: "/CareGuide/breeds/dogs/shih-tzu.jpg",
    expertReviewed: true,
    slug: "puppy-vaccination-schedule-guide",
  },
  {
    id: "dachshund-spine-ivdd-prevention",
    title: "IVDD Prevention & Ramp Training for Long Backs",
    excerpt: "Protect chondrodystrophic spines from herniated discs through core conditioning, no-jump sofa ramps, and supportive harnesses.",
    readTime: "7 min read",
    category: "Health & Vet Care",
    image: "/CareGuide/breeds/dogs/dachshund.jpg",
    expertReviewed: true,
    slug: "puppy-vaccination-schedule-guide",
  },
  {
    id: "mental-stimulation-scent-work",
    title: "Brain Games & Backyard Canine Scent Work",
    excerpt: "Channel instinctual olfactory drive with snuffle mats, hidden treat tracking, and puzzle feeders that tire dogs faster than runs.",
    readTime: "6 min read",
    category: "Behavior",
    image: "/CareGuide/breeds/dogs/pomeranian.jpg",
    expertReviewed: true,
    slug: "puppy-vaccination-schedule-guide",
  },
  {
    id: "dog-ear-cleaning-infection-prevention",
    title: "Floppy Ear Cleaning & Yeast Prevention",
    excerpt: "How to clean moisture-trapping hound ears safely using drying astringent flushes without damaging sensitive eardrums.",
    readTime: "5 min read",
    category: "Grooming",
    image: "/CareGuide/breeds/dogs/beagle.jpg",
    expertReviewed: true,
    slug: "puppy-vaccination-schedule-guide",
  },
  {
    id: "canine-leash-reactivity-counterconditioning",
    title: "Overcoming On-Leash Reactivity & Barking",
    excerpt: "Desensitize your dog to neighborhood triggers using look-at-that (LAT) marking, distance thresholds, and calm refocusing cues.",
    readTime: "8 min read",
    category: "Behavior",
    image: "/CareGuide/breeds/dogs/german-shepherd.jpg",
    expertReviewed: true,
    slug: "puppy-vaccination-schedule-guide",
  },
  {
    id: "puppy-teething-chew-toy-guide",
    title: "Puppy Teething Relief & Furniture Protection",
    excerpt: "Soften sore gums with frozen washcloths and edible dental rings while redirecting destructive puppy nipping away from hands.",
    readTime: "5 min read",
    category: "Life Stage",
    image: "/CareGuide/breeds/dogs/golden-retriever.jpg",
    expertReviewed: true,
    slug: "puppy-vaccination-schedule-guide",
  },
  {
    id: "dog-microchip-registration-safety",
    title: "Microchipping, Collars & Lost Pet Recovery",
    excerpt: "Everything you need to know about ISO universal microchip frequency scanners, registry contact updates, and GPS backup collars.",
    readTime: "6 min read",
    category: "General Care",
    image: "/CareGuide/categories/dog.png",
    expertReviewed: true,
    slug: "puppy-vaccination-schedule-guide",
  },
];

export const CAT_CARE_ARTICLES: CareArticleCardData[] = [
  {
    id: "teach-kitten-simple-cues",
    title: "Teach Your New Kitten Simple Cues",
    excerpt: "Target stick training, gentle recall, and rewarding polite manners in cats with positive reinforcement and delicious lickable treats.",
    readTime: "6 min read",
    category: "Training",
    image: "/CareGuide/breeds/cats/persian.jpg",
    expertReviewed: true,
    slug: "teach-new-kitten-simple-cues",
  },
  {
    id: "feline-urinary-tract-health",
    title: "Feline Hydration & Urinary Tract Health",
    excerpt: "Wet food moisture ratios, circulating fountains, and early indicators of FLUTD and crystal blockages in vulnerable male cats.",
    readTime: "7 min read",
    category: "Health & Vet Care",
    image: "/CareGuide/breeds/cats/british-shorthair.jpg",
    expertReviewed: true,
    slug: "teach-new-kitten-simple-cues",
  },
  {
    id: "scratching-post-mastery",
    title: "Scratching Post Selection & Cat Body Language",
    excerpt: "Understand territorial pheromone marking, horizontal vs. vertical scratch preferences, and redirecting clawing instincts safely.",
    readTime: "5 min read",
    category: "Behavior",
    image: "/CareGuide/breeds/cats/siamese.jpg",
    expertReviewed: true,
    slug: "teach-new-kitten-simple-cues",
  },
  {
    id: "brushing-longhaired-cats",
    title: "Grooming Long-Haired Breeds Without Stress",
    excerpt: "Preventing painful trichobezoar hairballs, detangling dense mane ruffs, and safe claw maintenance tips without scruffing.",
    readTime: "6 min read",
    category: "Grooming",
    image: "/CareGuide/breeds/cats/maine-coon.jpg",
    expertReviewed: true,
    slug: "teach-new-kitten-simple-cues",
  },
  {
    id: "indoor-enrichment-for-cats",
    title: "Vertical Spaces & Indoor Enrichment",
    excerpt: "Cat wall perches, food foraging puzzles, and structured predatory play sequences that banish boredom and nighttime zoomies.",
    readTime: "8 min read",
    category: "Behavior",
    image: "/CareGuide/breeds/cats/bengal.jpg",
    expertReviewed: true,
    slug: "teach-new-kitten-simple-cues",
  },
  {
    id: "kitten-first-year-milestones",
    title: "First-Year Kitten Growth & Nutrition",
    excerpt: "High-protein feeding curves, spay and neuter recovery protocols, core FVRCP vaccines, and critical behavioral socialization windows.",
    readTime: "7 min read",
    category: "Life Stage",
    image: "/CareGuide/breeds/cats/ragdoll.jpg",
    expertReviewed: true,
    slug: "teach-new-kitten-simple-cues",
  },
  {
    id: "hairball-dietary-prevention",
    title: "Hairball Remedies & Balanced Fiber Diets",
    excerpt: "Natural insoluble fiber blends, pumpkin purees, and gentle malt enzymatics that ease hairball transit through the digestive tract.",
    readTime: "5 min read",
    category: "Nutrition",
    image: "/CareGuide/breeds/cats/russian-blue.jpg",
    expertReviewed: true,
    slug: "teach-new-kitten-simple-cues",
  },
  {
    id: "dental-hygiene-in-cats",
    title: "Preventing Periodontal Disease in Cats",
    excerpt: "Enzymatic poultry tooth gels, water additives, and annual veterinary ultrasonic scaling checks to prevent feline tooth resorption.",
    readTime: "6 min read",
    category: "Health & Vet Care",
    image: "/CareGuide/breeds/cats/scottish-fold.jpg",
    expertReviewed: true,
    slug: "teach-new-kitten-simple-cues",
  },
  {
    id: "sphynx-hairless-skin-bathing",
    title: "Sphynx & Hairless Cat Skin Care Regimen",
    excerpt: "Sebum regulation, warm hypoallergenic sponge baths, sun protection, and weekly ear wax cleaning routines for naked breeds.",
    readTime: "5 min read",
    category: "Grooming",
    image: "/CareGuide/breeds/cats/sphynx.jpg",
    expertReviewed: true,
    slug: "teach-new-kitten-simple-cues",
  },
  {
    id: "multi-cat-peace-resource-guarding",
    title: "Multi-Cat Harmony: Solving Litter Box Bullying",
    excerpt: "The golden n+1 litter rule, separate microchip feeders, and escape routes to resolve silent guarding and territorial disputes.",
    readTime: "7 min read",
    category: "Behavior",
    image: "/CareGuide/breeds/cats/calico.jpg",
    expertReviewed: true,
    slug: "teach-new-kitten-simple-cues",
  },
  {
    id: "senior-cat-renal-kidney-health",
    title: "Senior Feline Kidney Wellness & Hydration",
    excerpt: "Low-phosphorus diets, subcutaneous hydration guidance, blood pressure monitoring, and warming wet food for older feline appetites.",
    readTime: "8 min read",
    category: "Health & Vet Care",
    image: "/CareGuide/categories/cat.png",
    expertReviewed: true,
    slug: "teach-new-kitten-simple-cues",
  },
  {
    id: "cat-leash-walking-adventure-training",
    title: "Harness Training & Safe Outdoor Walking",
    excerpt: "Conditioning your cat to lightweight escape-proof H-harnesses and enjoying low-stress backyard patio exploration.",
    readTime: "6 min read",
    category: "Training",
    image: "/CareGuide/breeds/cats/bengal.jpg",
    expertReviewed: true,
    slug: "teach-new-kitten-simple-cues",
  },
  {
    id: "cat-litter-box-aversion-solutions",
    title: "Solving Inappropriate Elimination & Litter Aversion",
    excerpt: "Unscented clumping litter selection, box depth preferences, and medical differential diagnoses for cats peeing outside the box.",
    readTime: "7 min read",
    category: "Behavior",
    image: "/CareGuide/breeds/cats/siamese.jpg",
    expertReviewed: true,
    slug: "teach-new-kitten-simple-cues",
  },
  {
    id: "feline-diabetes-low-carb-nutrition",
    title: "Feline Diabetes & Low-Carb Nutrition Principles",
    excerpt: "Why obligate carnivores thrive on high-protein, zero-starch diets, and how proper wet food feeding supports diabetic remission.",
    readTime: "7 min read",
    category: "Nutrition",
    image: "/CareGuide/breeds/cats/british-shorthair.jpg",
    expertReviewed: true,
    slug: "teach-new-kitten-simple-cues",
  },
  {
    id: "cat-eye-discharge-conjunctivitis",
    title: "Feline Herpesvirus & Eye Discharge Care",
    excerpt: "Understanding upper respiratory flare-ups, L-lysine supplementation, warm compresses, and safe prescription eye drops.",
    readTime: "5 min read",
    category: "Health & Vet Care",
    image: "/CareGuide/breeds/cats/persian.jpg",
    expertReviewed: true,
    slug: "teach-new-kitten-simple-cues",
  },
  {
    id: "cat-carrier-desensitization-vet-visits",
    title: "Stress-Free Vet Visits: Carrier Training",
    excerpt: "Turn the scary travel carrier into a cozy bedroom retreat using pheromone sprays and positive mealtime association.",
    readTime: "5 min read",
    category: "Training",
    image: "/CareGuide/breeds/cats/ragdoll.jpg",
    expertReviewed: true,
    slug: "teach-new-kitten-simple-cues",
  },
];

export const SMALL_PETS_CARE_ARTICLES: CareArticleCardData[] = [
  {
    id: "rabbit-diet-timothy-hay",
    title: "The 80% Rule: Why Timothy Hay is Vital for Rabbits",
    excerpt: "Prevent life-threatening GI stasis, promote constant intestinal peristalsis, and grind down fast-growing molar teeth with high-fiber first-cut hay.",
    readTime: "6 min read",
    category: "Nutrition",
    image: "/CareGuide/breeds/small-pets/holland-lop.jpg",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
  {
    id: "guinea-pig-vitamin-c-guide",
    title: "Essential Daily Vitamin C for Guinea Pigs",
    excerpt: "Recognize scurvy deficiency symptoms, measure safe fresh bell pepper slices, and choose stabilized chewable vitamin supplements over water drops.",
    readTime: "5 min read",
    category: "Health & Vet Care",
    image: "/CareGuide/breeds/small-pets/guinea-pig.jpg",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
  {
    id: "hamster-burrow-habitat-setup",
    title: "Creating Deep Burrowing Habitats for Hamsters",
    excerpt: "Choose unbroken floor tanks over barred cages, layer 10+ inches of low-dust aspen paper, and install sanitized calcium-free volcanic sand baths.",
    readTime: "7 min read",
    category: "Behavior",
    image: "/CareGuide/breeds/small-pets/syrian-hamster.jpg",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
  {
    id: "chinchilla-dust-bath-care",
    title: "Chinchilla Dust Baths & Fur Maintenance",
    excerpt: "Why water baths cause deadly skin fungus in dense chinchilla coats, and how volcanic pumice dust keeps fur silky and grease-free.",
    readTime: "4 min read",
    category: "Grooming",
    image: "/CareGuide/breeds/small-pets/chinchilla.jpg",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
  {
    id: "ferret-enrichment-rabbit-litter",
    title: "Ferret Play-Proofing & Litter Box Habits",
    excerpt: "Secure appliance crevices, build crinkle tube mazes, and use low-entry triangular litter boxes with paper pellet substrate.",
    readTime: "6 min read",
    category: "Training",
    image: "/CareGuide/breeds/small-pets/ferret.jpg",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
  {
    id: "hedgehog-temperature-wellness",
    title: "African Pygmy Hedgehog Temperature Control",
    excerpt: "Prevent dangerous hibernation lethargy by maintaining 74–78°F ambient warmth using ceramic heat emitters hooked to digital pulse thermostats.",
    readTime: "6 min read",
    category: "Health & Vet Care",
    image: "/CareGuide/breeds/small-pets/hedgehog.jpg",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
  {
    id: "small-pet-dental-health",
    title: "Detecting Malocclusion in Pocket Pets",
    excerpt: "Early clinical signs of overgrown incisors and cheek spurs: chin drooling, watery eyes, selective eating, and veterinary floating procedures.",
    readTime: "5 min read",
    category: "Health & Vet Care",
    image: "/CareGuide/breeds/small-pets/netherland-dwarf.jpg",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
  {
    id: "safe-foraging-herbs-greens",
    title: "Fresh Herb & Foraging Guide for Small Herbivores",
    excerpt: "Safe calcium-to-phosphorus ratios for cilantro, dill, mint, and romaine versus high-oxalate spinach and gas-producing cruciferous vegetables.",
    readTime: "5 min read",
    category: "Nutrition",
    image: "/CareGuide/categories/rabbit.png",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
  {
    id: "rabbit-bunny-bonding-protocol",
    title: "Bonding Rabbits: The 2-Week Neutral Territory Method",
    excerpt: "Establish peaceful lifelong companion bonds using parallel pen setups, mutual stress rides, and gradual grooming breakthroughs.",
    readTime: "7 min read",
    category: "Behavior",
    image: "/CareGuide/breeds/small-pets/holland-lop.jpg",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
  {
    id: "hamster-upright-wheel-spine-health",
    title: "Choosing Safe Hamster Running Wheels",
    excerpt: "Prevent painful spinal curvature and bumblefoot by selecting solid 11-12 inch wheels with zero crossbars or dangerous wire mesh rungs.",
    readTime: "5 min read",
    category: "General Care",
    image: "/CareGuide/breeds/small-pets/syrian-hamster.jpg",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
  {
    id: "guinea-pig-popcorning-vocalizations",
    title: "Understanding Guinea Pig Wheeks & Popcorning",
    excerpt: "Decode high-pitched refrigerator wheeks, purring contentment, and playful acrobatic jumping signals of pure rodent happiness.",
    readTime: "5 min read",
    category: "Behavior",
    image: "/CareGuide/breeds/small-pets/guinea-pig.jpg",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
  {
    id: "chinchilla-safe-wooden-chews",
    title: "Kiln-Dried Chews for Chinchilla Dental Wear",
    excerpt: "Which fruitwoods like apple and willow are safe versus toxic resinous cedar, and how daily gnawing prevents tooth impaction.",
    readTime: "4 min read",
    category: "Nutrition",
    image: "/CareGuide/breeds/small-pets/chinchilla.jpg",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
];

export const AQUATIC_CARE_ARTICLES: CareArticleCardData[] = [
  {
    id: "nitrogen-cycle-tank-setup",
    title: "Mastering the Nitrogen Cycle: 0 to Cycled Tank",
    excerpt: "Nurture nitrosomonas and nitrobacter colonies to convert lethal ammonia into nitrites and stable nitrates before adding aquatic life.",
    readTime: "8 min read",
    category: "General Care",
    image: "/CareGuideCard/aquatic-care-guide-bg.png",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
  {
    id: "betta-fish-habitat-heating",
    title: "The Modern Betta: Moving Beyond Tiny Bowls",
    excerpt: "Why labyrinth organs still require 5+ gallons of heated, filtered, low-flow water with soft silk or live broad-leaf hammock plants.",
    readTime: "6 min read",
    category: "General Care",
    image: "/CareGuide/breeds/aquatic/betta.jpg",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
  {
    id: "fancy-goldfish-diet-swimbladder",
    title: "Fancy Goldfish Nutrition & Swim Bladder Prevention",
    excerpt: "Prevent intestinal air gulps with sinking pellets, soaked gel foods, boiled green peas, and heavy bio-filtration for high-waste carps.",
    readTime: "7 min read",
    category: "Nutrition",
    image: "/CareGuide/breeds/aquatic/goldfish.jpg",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
  {
    id: "live-aquarium-plants-low-tech",
    title: "Top 7 Easy Live Plants for Natural Filtration",
    excerpt: "Grow low-light Anubias, Java Fern, and Amazon Swords to consume nitrates, outcompete brown algae, and oxygenate aquarium water naturally.",
    readTime: "5 min read",
    category: "General Care",
    image: "/CareGuide/breeds/aquatic/angelfish.jpg",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
  {
    id: "guppy-breeding-water-hardness",
    title: "Guppy Care, Water Hardness & Colony Harmony",
    excerpt: "Maintain optimal 1:2 male-to-female ratios, mineral-rich general hardness (GH), and dense moss hiding zones for fry survival.",
    readTime: "5 min read",
    category: "Life Stage",
    image: "/CareGuide/breeds/aquatic/guppies.jpg",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
  {
    id: "saltwater-clownfish-anemone-basics",
    title: "Marine Nano Tank & Clownfish Hosting Basics",
    excerpt: "Essential hydrometer salinity monitoring (1.024-1.026 SG), coral-safe LED spectra, and gentle protein skimming for marine setups.",
    readTime: "9 min read",
    category: "Behavior",
    image: "/CareGuide/breeds/aquatic/clownfish.jpg",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
  {
    id: "preventing-aquarium-ich-disease",
    title: "Spotting & Treating White Spot (Ich) Disease",
    excerpt: "Disrupt the tomont reproductive cycle with gradual 86°F temperature elevation, aquarium salt dips, and scaleless-safe herbal remedies.",
    readTime: "6 min read",
    category: "Health & Vet Care",
    image: "/CareGuide/categories/fish.png",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
  {
    id: "feeding-schedules-preventing-ammonia",
    title: "Optimal Feeding Schedules & Avoiding Overfeeding",
    excerpt: "Why the strict 2-minute rule prevents toxic ammonia spikes, swim bladder disorders, and unsightly green water algae explosions.",
    readTime: "4 min read",
    category: "Nutrition",
    image: "/CareGuide/breeds/aquatic/angelfish.jpg",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
  {
    id: "planted-aquarium-algae-control",
    title: "Defeating Black Beard & Diatom Algae Organically",
    excerpt: "Balance photoperiod timers, liquid carbon dosing, and enlist clean-up crews like Amano shrimp and Otocinclus catfish.",
    readTime: "6 min read",
    category: "General Care",
    image: "/CareGuide/breeds/aquatic/goldfish.jpg",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
  {
    id: "freshwater-angelfish-territoriality",
    title: "Angelfish Pair Bonding & Tall Tank Heights",
    excerpt: "Vertical tank space requirements, cichlid territorial aggression during spawning, and peaceful tetras to avoid fin-nipping.",
    readTime: "7 min read",
    category: "Behavior",
    image: "/CareGuide/breeds/aquatic/angelfish.jpg",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
  {
    id: "aquarium-water-testing-master-kit",
    title: "Decoding Liquid Water Test Parameters: pH, GH & KH",
    excerpt: "Move beyond unreliable paper strips: interpret exact color reagent titration results for rock-solid water chemistry stability.",
    readTime: "7 min read",
    category: "Health & Vet Care",
    image: "/CareGuideCard/aquatic-care-guide-bg.png",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
  {
    id: "neon-tetra-schooling-behavior",
    title: "Creating Lush Amazonian Biotope Blackwater Tanks",
    excerpt: "Add Indian almond leaves and driftwood tannins to reduce pathogen counts, lower pH safely, and prompt vibrant schooling behavior.",
    readTime: "6 min read",
    category: "General Care",
    image: "/CareGuide/breeds/aquatic/betta.jpg",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
];

export const REPTILES_CARE_ARTICLES: CareArticleCardData[] = [
  {
    id: "uvb-lighting-metabolic-bone-disease",
    title: "UVB Lighting & Preventing Metabolic Bone Disease",
    excerpt: "The critical difference between T5 High Output fluorescent tubes and coil bulbs: Ferguson zone charts and yearly bulb decay schedules.",
    readTime: "8 min read",
    category: "Health & Vet Care",
    image: "/CareGuide/breeds/reptiles/bearded-dragon.jpg",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
  {
    id: "bearded-dragon-salad-feeder-ratios",
    title: "Bearded Dragon Nutrition: Juvenile vs. Adult Ratios",
    excerpt: "Transition safely from 80% gut-loaded Dubia roaches as juveniles to 80% calcium-rich collard and dandelion greens as mature adults.",
    readTime: "7 min read",
    category: "Nutrition",
    image: "/CareGuide/featured/reptile-guide.jpg",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
  {
    id: "leopard-gecko-calcium-shedding-care",
    title: "Leopard Gecko Moist Hide & Shedding Aid",
    excerpt: "Prevent necrotic retained toe skin with sphagnum moss humid hides and offer pure calcium carbonate dishes in enclosure corners.",
    readTime: "5 min read",
    category: "Grooming",
    image: "/CareGuide/breeds/reptiles/leopard-gecko.jpg",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
  {
    id: "chameleon-hydration-screen-enclosures",
    title: "Chameleon Droplet Hydration & Screen Ventilation",
    excerpt: "Why veiled and panther chameleons need automated timed pressure misting, living ficus foliage, and continuous cross-draft airflow.",
    readTime: "6 min read",
    category: "Behavior",
    image: "/CareGuide/breeds/reptiles/chameleon.jpg",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
  {
    id: "aquatic-turtle-filtration-basking",
    title: "Red-Eared Slider & Turtle Basking Platforms",
    excerpt: "High-volume canister filtration rated 3x tank size, complete dry-out basking docks, and water heaters with protective plastic guards.",
    readTime: "7 min read",
    category: "General Care",
    image: "/CareGuide/breeds/reptiles/turtle.jpg",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
  {
    id: "reptile-temperature-gradients",
    title: "Designing Precision Thermal Gradients",
    excerpt: "Establish distinct 105°F basking spots and 75°F ambient cool retreats using overhead halogen floodlights and digital probe thermometers.",
    readTime: "6 min read",
    category: "General Care",
    image: "/CareGuide/categories/reptile.png",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
  {
    id: "handling-and-taming-juvenile-reptiles",
    title: "Gentle Taming & Handling Protocols",
    excerpt: "Build handling tolerance without triggering defensive mouth gaping or tail loss by scooping from underneath instead of predator grabs.",
    readTime: "5 min read",
    category: "Training",
    image: "/CareGuide/breeds/reptiles/bearded-dragon.jpg",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
  {
    id: "calcium-multivitamin-dusting-schedules",
    title: "Feeder Insect Gut-Loading & Calcium Dusting",
    excerpt: "Feed insects fresh squash and bee pollen 24 hours prior to feeding, alternating phosphorus-free calcium with Vitamin D3/multivitamin powders.",
    readTime: "5 min read",
    category: "Nutrition",
    image: "/CareGuide/breeds/reptiles/leopard-gecko.jpg",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
  {
    id: "bioactive-terrarium-cleanup-crews",
    title: "Bioactive Vivarium Setup with Isopods & Springtails",
    excerpt: "Build self-cleaning enclosed ecosystems with drainage layers, live tropical plants, microfauna detritivores, and organic leaf litter.",
    readTime: "8 min read",
    category: "General Care",
    image: "/CareGuide/breeds/reptiles/chameleon.jpg",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
  {
    id: "crested-gecko-pangea-diet-care",
    title: "Crested Gecko Fruit Powder & No-Heat Care",
    excerpt: "Complete powdered meal replacement formulas, vertical cork bark foliage, and why room temperatures (72-76°F) are ideal for cresties.",
    readTime: "6 min read",
    category: "Nutrition",
    image: "/CareGuide/featured/reptile-guide.jpg",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
  {
    id: "reptile-respiratory-infection-signs",
    title: "Spotting Respiratory Infections in Reptiles Early",
    excerpt: "Recognize bubble mucus, wheezing, and mouth breathing caused by cold damp drafts, and learn proper emergency quarantine heating.",
    readTime: "7 min read",
    category: "Health & Vet Care",
    image: "/CareGuide/breeds/reptiles/bearded-dragon.jpg",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
  {
    id: "ball-python-humidity-shedding-box",
    title: "Managing Snake Humidity & Complete Eyecap Sheds",
    excerpt: "Achieve clean one-piece sheds by boosting ambient humidity to 70% with coco husk substrate and damp moss hide retreats.",
    readTime: "6 min read",
    category: "Grooming",
    image: "/CareGuide/breeds/reptiles/turtle.jpg",
    expertReviewed: true,
    slug: "budgie-care-guide",
  },
];

export const CATEGORY_ARTICLES_MAP: Record<string, CareArticleCardData[]> = {
  birds: BUDGIE_CARE_ARTICLES,
  dogs: DOG_CARE_ARTICLES,
  cats: CAT_CARE_ARTICLES,
  "small-pets": SMALL_PETS_CARE_ARTICLES,
  aquatic: AQUATIC_CARE_ARTICLES,
  reptiles: REPTILES_CARE_ARTICLES,
};
