import { PetCareGuideCardData } from "./PetCareGuideCard";

export const PET_SPECIES_FEATURED_GUIDES: Record<string, PetCareGuideCardData> = {
  birds: {
    badgeText: "Start Here",
    badgeIcon: "👑",
    title: "The Complete Budgie Care Guide",
    description:
      "Everything you need to know to give your budgie a healthy, happy life. From housing and diet to training and health care.",
    readTime: "12 min read",
    expertReviewed: true,
    ctaText: "Read Full Guide",
    href: "/guides/budgie-care-guide",
    image: "/CareGuideCard/budgie-care-guide-bg.png",
    imageAlt: "Pet blue budgie perched on a branch",
    slogan: "Happy budgies brighter homes",
    heartIcon: true,
    bgGradient: "bg-linear-to-r from-[#eef9f2] via-[#e5f5ed] to-[#d8efe5] dark:from-[#11231a] dark:via-[#13271c] dark:to-[#173024]",
    bubbleColor: "bg-[#c6ebd7]/60 dark:bg-[#1f4230]/40",
    blendOverlayClass: "bg-linear-to-r from-[#eef9f2] via-[#eef9f2]/90 via-40% sm:via-[#eef9f2]/75 sm:via-50% md:via-[#eef9f2]/40 md:via-60% to-transparent dark:from-[#11231a] dark:via-[#11231a]/95 dark:via-40% sm:dark:via-[#11231a]/80 sm:dark:via-50% md:dark:via-[#11231a]/40 md:dark:via-60% dark:to-transparent",
  },
  cockatiel: {
    badgeText: "Bird Favorite",
    badgeIcon: "🦜",
    title: "The Essential Cockatiel Care Guide",
    description:
      "A complete guide to cockatiel whistling, foraging toys, cage requirements, and essential seed and pellet nutrition.",
    readTime: "9 min read",
    expertReviewed: true,
    ctaText: "Read Cockatiel Guide",
    href: "/guides",
    image: "/CareGuideCard/cockatiel-care-guide-bg.png",
    imageAlt: "Cute cockatiel with orange cheeks perched on a branch",
    slogan: "Whistle and song all day long",
    heartIcon: true,
    bgGradient: "bg-linear-to-r from-[#fffde7] via-[#fff9c4] to-[#fff59d] dark:from-[#262210] dark:via-[#2b2713] dark:to-[#332f18]",
    bubbleColor: "bg-[#fff59d]/50 dark:bg-[#4d441c]/40",
    blendOverlayClass: "bg-linear-to-r from-[#fffde7] via-[#fffde7]/90 via-40% sm:via-[#fffde7]/75 sm:via-50% md:via-[#fffde7]/40 md:via-60% to-transparent dark:from-[#262210] dark:via-[#262210]/95 dark:via-40% sm:dark:via-[#262210]/80 sm:dark:via-50% md:dark:via-[#262210]/40 md:dark:via-60% dark:to-transparent",
  },
  dogs: {
    badgeText: "Puppy Essential",
    badgeIcon: "🐾",
    title: "The Complete Puppy & Dog Care Guide",
    description:
      "A vet-approved guide to puppy vaccinations, balanced canine nutrition, positive reinforcement training, and socialization.",
    readTime: "10 min read",
    expertReviewed: true,
    ctaText: "Read Dog Guide",
    href: "/guides/puppy-vaccination-schedule-guide",
    image: "/CareGuideCard/dog-care-guide-bg.png",
    imageAlt: "Happy golden dog looking forward in a sunny meadow",
    slogan: "Loyal companions lifelong health",
    heartIcon: true,
    bgGradient: "bg-linear-to-r from-[#fff9eb] via-[#fff4dc] to-[#faecd0] dark:from-[#251e13] dark:via-[#2c2317] dark:to-[#33281b]",
    bubbleColor: "bg-[#ffe0b2]/50 dark:bg-[#4d3b24]/40",
    blendOverlayClass: "bg-linear-to-r from-[#fff9eb] via-[#fff9eb]/90 via-40% sm:via-[#fff9eb]/75 sm:via-50% md:via-[#fff9eb]/40 md:via-60% to-transparent dark:from-[#251e13] dark:via-[#251e13]/95 dark:via-40% sm:dark:via-[#251e13]/80 sm:dark:via-50% md:dark:via-[#251e13]/40 md:dark:via-60% dark:to-transparent",
  },
  cats: {
    badgeText: "Kitten Care",
    badgeIcon: "🐱",
    title: "Essential Feline Care & Training Guide",
    description:
      "Teach your new kitten simple cues, set up an enriching indoor environment, and maintain optimal feline nutritional health.",
    readTime: "8 min read",
    expertReviewed: true,
    ctaText: "Read Cat Guide",
    href: "/guides/teach-new-kitten-simple-cues",
    image: "/CareGuideCard/cat-care-guide-bg.png",
    imageAlt: "Cute fluffy kitten looking up in a garden",
    slogan: "Curious paws contented purrs",
    heartIcon: true,
    bgGradient: "bg-linear-to-r from-[#fbf8f5] via-[#f7f2ed] to-[#ede3d8] dark:from-[#221c1a] dark:via-[#27211e] dark:to-[#2e2623]",
    bubbleColor: "bg-[#e8d5c4]/40 dark:bg-[#42332c]/40",
    blendOverlayClass: "bg-linear-to-r from-[#fbf8f5] via-[#fbf8f5]/90 via-40% sm:via-[#fbf8f5]/75 sm:via-50% md:via-[#fbf8f5]/40 md:via-60% to-transparent dark:from-[#221c1a] dark:via-[#221c1a]/95 dark:via-40% sm:dark:via-[#221c1a]/80 sm:dark:via-50% md:dark:via-[#221c1a]/40 md:dark:via-60% dark:to-transparent",
  },
  "small-pets": {
    badgeText: "Small Pets",
    badgeIcon: "🐹",
    title: "Pocket Pet Habitat & Nutrition Basics",
    description:
      "Learn safe bedding choices, healthy foraging diets, and essential dental care for hamsters, rabbits, and guinea pigs.",
    readTime: "7 min read",
    expertReviewed: true,
    ctaText: "Read Small Pets Guide",
    href: "/guides",
    image: "/CareGuide/featured/smallpet-guide.jpg",
    imageAlt: "Small hamster eating fresh seed",
    slogan: "Tiny friends boundless joy",
    heartIcon: true,
    bgGradient: "bg-linear-to-r from-[#fff3e0] via-[#ffe8cc] to-[#fedbb3] dark:from-[#261d14] dark:via-[#2e2217] dark:to-[#38281b]",
    bubbleColor: "bg-[#ffcc80]/40 dark:bg-[#4f3621]/40",
    blendOverlayClass: "bg-linear-to-r from-[#fff3e0] via-[#fff3e0]/75 sm:via-[#fff3e0]/40 to-transparent dark:from-[#261d14] dark:via-[#261d14]/90 sm:dark:via-[#261d14]/60 dark:to-transparent",
  },
  aquatic: {
    badgeText: "Aquarium Care",
    badgeIcon: "🐠",
    title: "Freshwater Aquarium Setup & Water Chemistry",
    description:
      "Master the nitrogen cycle, optimal filtration, heating requirements, and peaceful tank mate pairings for thriving fish.",
    readTime: "9 min read",
    expertReviewed: true,
    ctaText: "Read Aquatic Guide",
    href: "/guides",
    image: "/CareGuideCard/aquatic-care-guide-bg.png",
    imageAlt: "Colorful tropical goldfish and neons swimming in planted aquarium",
    slogan: "Crystal clear peaceful waters",
    heartIcon: true,
    bgGradient: "bg-linear-to-r from-[#e1f5fe] via-[#d0edf9] to-[#bfe4f5] dark:from-[#112431] dark:via-[#142b3b] dark:to-[#173347]",
    bubbleColor: "bg-[#81d4fa]/35 dark:bg-[#1a4057]/40",
    blendOverlayClass: "bg-linear-to-r from-[#e1f5fe] via-[#e1f5fe]/90 via-40% sm:via-[#e1f5fe]/75 sm:via-50% md:via-[#e1f5fe]/40 md:via-60% to-transparent dark:from-[#112431] dark:via-[#112431]/95 dark:via-40% sm:dark:via-[#112431]/80 sm:dark:via-50% md:dark:via-[#112431]/40 md:dark:via-60% dark:to-transparent",
  },
  reptiles: {
    badgeText: "Terrarium Guide",
    badgeIcon: "🦎",
    title: "Reptile Thermal Gradient & UVB Essentials",
    description:
      "Create proper basking zones, monitor humidity gradients, and supply correct calcium supplementation for reptiles.",
    readTime: "11 min read",
    expertReviewed: true,
    ctaText: "Read Reptile Guide",
    href: "/guides",
    image: "/CareGuide/featured/reptile-guide.jpg",
    imageAlt: "Bright green gecko on a natural branch",
    slogan: "Precision heat vibrant life",
    heartIcon: true,
    bgGradient: "bg-linear-to-r from-[#f1f8e9] via-[#e6f3dc] to-[#d7ecc9] dark:from-[#172613] dark:via-[#1b2c16] dark:to-[#21371c]",
    bubbleColor: "bg-[#c5e1a5]/40 dark:bg-[#284221]/40",
    blendOverlayClass: "bg-linear-to-r from-[#f1f8e9] via-[#f1f8e9]/75 sm:via-[#f1f8e9]/40 to-transparent dark:from-[#172613] dark:via-[#172613]/90 sm:dark:via-[#172613]/60 dark:to-transparent",
  },
};
