import { PetCareGuideCardData } from "./PetCareGuideCard";

export const PET_SPECIES_FEATURED_GUIDES: Record<string, PetCareGuideCardData> = {
  birds: {
    badgeText: "Start Here",
    badgeIcon: "👑",
    title: "The Complete Budgie Care Guide",
    description:
      "Everything you need to know to give your budgie a healthy, happy life. From housing and diet to training and health care.",
    readTime: "12 min read",
    expertReviewed: true,
    ctaText: "Read Full Guide",
    href: "/guides/budgie-care-guide",
    image: "/CareGuide/budgier.png",
    imageAlt: "Pet blue budgie perched on a branch",
    slogan: "Happy budgies brighter homes",
    heartIcon: true,
    bgGradient: "bg-linear-to-r from-[#eef9f2] via-[#e5f5ed] to-[#d8efe5]",
    bubbleColor: "bg-[#c6ebd7]/60",
    blendOverlayClass: "bg-linear-to-r from-[#eef9f2] via-[#eef9f2]/75 sm:via-[#eef9f2]/40 to-transparent",
  },
  dogs: {
    badgeText: "Puppy Essential",
    badgeIcon: "🐾",
    title: "The Complete Puppy & Dog Care Guide",
    description:
      "A vet-approved guide to puppy vaccinations, balanced canine nutrition, positive reinforcement training, and socialization.",
    readTime: "10 min read",
    expertReviewed: true,
    ctaText: "Read Dog Guide",
    href: "/guides/puppy-vaccination-schedule-guide",
    image: "/CareGuide/featured/dog-guide.jpg",
    imageAlt: "Happy golden dog looking forward",
    slogan: "Loyal companions lifelong health",
    heartIcon: true,
    bgGradient: "bg-linear-to-r from-[#fff9eb] via-[#fff4dc] to-[#faecd0]",
    bubbleColor: "bg-[#ffe0b2]/50",
    blendOverlayClass: "bg-linear-to-r from-[#fff9eb] via-[#fff9eb]/75 sm:via-[#fff9eb]/40 to-transparent",
  },
  cats: {
    badgeText: "Kitten Care",
    badgeIcon: "🐱",
    title: "Essential Feline Care & Training Guide",
    description:
      "Teach your new kitten simple cues, set up an enriching indoor environment, and maintain optimal feline nutritional health.",
    readTime: "8 min read",
    expertReviewed: true,
    ctaText: "Read Cat Guide",
    href: "/guides/teach-new-kitten-simple-cues",
    image: "/CareGuide/featured/cat-guide.jpg",
    imageAlt: "Cute cat with captivating eyes",
    slogan: "Curious paws contented purrs",
    heartIcon: true,
    bgGradient: "bg-linear-to-r from-[#f7f2fa] via-[#f0e8f6] to-[#e7daf0]",
    bubbleColor: "bg-[#e1bee7]/40",
    blendOverlayClass: "bg-linear-to-r from-[#f7f2fa] via-[#f7f2fa]/75 sm:via-[#f7f2fa]/40 to-transparent",
  },
  "small-pets": {
    badgeText: "Small Pets",
    badgeIcon: "🐹",
    title: "Pocket Pet Habitat & Nutrition Basics",
    description:
      "Learn safe bedding choices, healthy foraging diets, and essential dental care for hamsters, rabbits, and guinea pigs.",
    readTime: "7 min read",
    expertReviewed: true,
    ctaText: "Read Small Pets Guide",
    href: "/guides",
    image: "/CareGuide/featured/smallpet-guide.jpg",
    imageAlt: "Small hamster eating fresh seed",
    slogan: "Tiny friends boundless joy",
    heartIcon: true,
    bgGradient: "bg-linear-to-r from-[#fff3e0] via-[#ffe8cc] to-[#fedbb3]",
    bubbleColor: "bg-[#ffcc80]/40",
    blendOverlayClass: "bg-linear-to-r from-[#fff3e0] via-[#fff3e0]/75 sm:via-[#fff3e0]/40 to-transparent",
  },
  aquatic: {
    badgeText: "Aquarium Care",
    badgeIcon: "🐠",
    title: "Freshwater Aquarium Setup & Water Chemistry",
    description:
      "Master the nitrogen cycle, optimal filtration, heating requirements, and peaceful tank mate pairings for thriving fish.",
    readTime: "9 min read",
    expertReviewed: true,
    ctaText: "Read Aquatic Guide",
    href: "/guides",
    image: "/CareGuide/featured/aquatic-guide.jpg",
    imageAlt: "Colorful tropical freshwater fish swimming",
    slogan: "Crystal clear peaceful waters",
    heartIcon: true,
    bgGradient: "bg-linear-to-r from-[#e1f5fe] via-[#d0edf9] to-[#bfe4f5]",
    bubbleColor: "bg-[#81d4fa]/35",
    blendOverlayClass: "bg-linear-to-r from-[#e1f5fe] via-[#e1f5fe]/75 sm:via-[#e1f5fe]/40 to-transparent",
  },
  reptiles: {
    badgeText: "Terrarium Guide",
    badgeIcon: "🦎",
    title: "Reptile Thermal Gradient & UVB Essentials",
    description:
      "Create proper basking zones, monitor humidity gradients, and supply correct calcium supplementation for reptiles.",
    readTime: "11 min read",
    expertReviewed: true,
    ctaText: "Read Reptile Guide",
    href: "/guides",
    image: "/CareGuide/featured/reptile-guide.jpg",
    imageAlt: "Bright green gecko on a natural branch",
    slogan: "Precision heat vibrant life",
    heartIcon: true,
    bgGradient: "bg-linear-to-r from-[#f1f8e9] via-[#e6f3dc] to-[#d7ecc9]",
    bubbleColor: "bg-[#c5e1a5]/40",
    blendOverlayClass: "bg-linear-to-r from-[#f1f8e9] via-[#f1f8e9]/75 sm:via-[#f1f8e9]/40 to-transparent",
  },
};
